name: chicken_thoughts_notifications
description: Send a new Chicken Thought every day!

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: "^3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  lottie: ^3.3.2
  photo_view: ^0.15.0
  animations: ^2.1.1
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  dynamic_color: ^1.8.1
  appwrite: ^21.3.0
  url_launcher: ^6.3.2
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  app_settings: ^7.0.0
  appcheck: ^1.7.0
  tutorial_coach_mark: ^1.3.3
  smooth_page_indicator: ^2.0.1
  shimmer_animation: ^2.2.2+1
  path_provider: ^2.1.5
  path: ^1.9.1
  proper_filesize: ^1.0.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/

flutter_launcher_icons:
  android: true
  web:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#fafafa"
  color_dark: "#303030"
  image: assets/icon.png

  android_12:
    image: assets/icon.png
    color: "#fafafa"
    color_dark: "#303030"